/*
Copyright 2021 Mirantis
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta2 "github.com/k0sproject/k0s/pkg/autopilot/apis/autopilot.k0sproject.io/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// FakeUpdateConfigLists implements UpdateConfigListInterface
type FakeUpdateConfigLists struct {
	Fake *FakeAutopilotV1beta2
}

var updateconfiglistsResource = schema.GroupVersionResource{Group: "autopilot.k0sproject.io", Version: "v1beta2", Resource: "updateconfiglists"}

var updateconfiglistsKind = schema.GroupVersionKind{Group: "autopilot.k0sproject.io", Version: "v1beta2", Kind: "UpdateConfigList"}

// Create takes the representation of a updateConfigList and creates it.  Returns the server's representation of the updateConfigList, and an error, if there is any.
func (c *FakeUpdateConfigLists) Create(ctx context.Context, updateConfigList *v1beta2.UpdateConfigList, opts v1.CreateOptions) (result *v1beta2.UpdateConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(updateconfiglistsResource, updateConfigList), &v1beta2.UpdateConfigList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpdateConfigList), err
}
