/*
Copyright 2021 Mirantis
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta2 "github.com/k0sproject/k0s/pkg/autopilot/apis/autopilot.k0sproject.io/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// FakeControlNodeLists implements ControlNodeListInterface
type FakeControlNodeLists struct {
	Fake *FakeAutopilotV1beta2
}

var controlnodelistsResource = schema.GroupVersionResource{Group: "autopilot.k0sproject.io", Version: "v1beta2", Resource: "controlnodelists"}

var controlnodelistsKind = schema.GroupVersionKind{Group: "autopilot.k0sproject.io", Version: "v1beta2", Kind: "ControlNodeList"}

// Create takes the representation of a controlNodeList and creates it.  Returns the server's representation of the controlNodeList, and an error, if there is any.
func (c *FakeControlNodeLists) Create(ctx context.Context, controlNodeList *v1beta2.ControlNodeList, opts v1.CreateOptions) (result *v1beta2.ControlNodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(controlnodelistsResource, controlNodeList), &v1beta2.ControlNodeList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.ControlNodeList), err
}
