// SPDX-FileCopyrightText: k0s authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	etcdv1beta1 "github.com/k0sproject/k0s/pkg/apis/etcd/v1beta1"
	scheme "github.com/k0sproject/k0s/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EtcdMembersGetter has a method to return a EtcdMemberInterface.
// A group's client should implement this interface.
type EtcdMembersGetter interface {
	EtcdMembers() EtcdMemberInterface
}

// EtcdMemberInterface has methods to work with EtcdMember resources.
type EtcdMemberInterface interface {
	Create(ctx context.Context, etcdMember *etcdv1beta1.EtcdMember, opts v1.CreateOptions) (*etcdv1beta1.EtcdMember, error)
	Update(ctx context.Context, etcdMember *etcdv1beta1.EtcdMember, opts v1.UpdateOptions) (*etcdv1beta1.EtcdMember, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, etcdMember *etcdv1beta1.EtcdMember, opts v1.UpdateOptions) (*etcdv1beta1.EtcdMember, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*etcdv1beta1.EtcdMember, error)
	List(ctx context.Context, opts v1.ListOptions) (*etcdv1beta1.EtcdMemberList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *etcdv1beta1.EtcdMember, err error)
	EtcdMemberExpansion
}

// etcdMembers implements EtcdMemberInterface
type etcdMembers struct {
	*gentype.ClientWithList[*etcdv1beta1.EtcdMember, *etcdv1beta1.EtcdMemberList]
}

// newEtcdMembers returns a EtcdMembers
func newEtcdMembers(c *EtcdV1beta1Client) *etcdMembers {
	return &etcdMembers{
		gentype.NewClientWithList[*etcdv1beta1.EtcdMember, *etcdv1beta1.EtcdMemberList](
			"etcdmembers",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *etcdv1beta1.EtcdMember { return &etcdv1beta1.EtcdMember{} },
			func() *etcdv1beta1.EtcdMemberList { return &etcdv1beta1.EtcdMemberList{} },
		),
	}
}
