// SPDX-FileCopyrightText: k0s authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "github.com/k0sproject/k0s/pkg/client/clientset/typed/autopilot/v1beta2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAutopilotV1beta2 struct {
	*testing.Fake
}

func (c *FakeAutopilotV1beta2) ControlNodes() v1beta2.ControlNodeInterface {
	return newFakeControlNodes(c)
}

func (c *FakeAutopilotV1beta2) Plans() v1beta2.PlanInterface {
	return newFakePlans(c)
}

func (c *FakeAutopilotV1beta2) UpdateConfigs() v1beta2.UpdateConfigInterface {
	return newFakeUpdateConfigs(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAutopilotV1beta2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
