// SPDX-FileCopyrightText: k0s authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "github.com/k0sproject/k0s/pkg/apis/autopilot/v1beta2"
	autopilotv1beta2 "github.com/k0sproject/k0s/pkg/client/clientset/typed/autopilot/v1beta2"
	gentype "k8s.io/client-go/gentype"
)

// fakeControlNodes implements ControlNodeInterface
type fakeControlNodes struct {
	*gentype.FakeClientWithList[*v1beta2.ControlNode, *v1beta2.ControlNodeList]
	Fake *FakeAutopilotV1beta2
}

func newFakeControlNodes(fake *FakeAutopilotV1beta2) autopilotv1beta2.ControlNodeInterface {
	return &fakeControlNodes{
		gentype.NewFakeClientWithList[*v1beta2.ControlNode, *v1beta2.ControlNodeList](
			fake.Fake,
			"",
			v1beta2.SchemeGroupVersion.WithResource("controlnodes"),
			v1beta2.SchemeGroupVersion.WithKind("ControlNode"),
			func() *v1beta2.ControlNode { return &v1beta2.ControlNode{} },
			func() *v1beta2.ControlNodeList { return &v1beta2.ControlNodeList{} },
			func(dst, src *v1beta2.ControlNodeList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta2.ControlNodeList) []*v1beta2.ControlNode { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta2.ControlNodeList, items []*v1beta2.ControlNode) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
