// SPDX-FileCopyrightText: k0s authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "github.com/k0sproject/k0s/pkg/apis/autopilot/v1beta2"
	autopilotv1beta2 "github.com/k0sproject/k0s/pkg/client/clientset/typed/autopilot/v1beta2"
	gentype "k8s.io/client-go/gentype"
)

// fakeUpdateConfigs implements UpdateConfigInterface
type fakeUpdateConfigs struct {
	*gentype.FakeClientWithList[*v1beta2.UpdateConfig, *v1beta2.UpdateConfigList]
	Fake *FakeAutopilotV1beta2
}

func newFakeUpdateConfigs(fake *FakeAutopilotV1beta2) autopilotv1beta2.UpdateConfigInterface {
	return &fakeUpdateConfigs{
		gentype.NewFakeClientWithList[*v1beta2.UpdateConfig, *v1beta2.UpdateConfigList](
			fake.Fake,
			"",
			v1beta2.SchemeGroupVersion.WithResource("updateconfigs"),
			v1beta2.SchemeGroupVersion.WithKind("UpdateConfig"),
			func() *v1beta2.UpdateConfig { return &v1beta2.UpdateConfig{} },
			func() *v1beta2.UpdateConfigList { return &v1beta2.UpdateConfigList{} },
			func(dst, src *v1beta2.UpdateConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta2.UpdateConfigList) []*v1beta2.UpdateConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta2.UpdateConfigList, items []*v1beta2.UpdateConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
