/*
Copyright k0s authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta2 "github.com/k0sproject/k0s/pkg/apis/autopilot/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePlans implements PlanInterface
type FakePlans struct {
	Fake *FakeAutopilotV1beta2
}

var plansResource = v1beta2.SchemeGroupVersion.WithResource("plans")

var plansKind = v1beta2.SchemeGroupVersion.WithKind("Plan")

// Get takes name of the plan, and returns the corresponding plan object, and an error if there is any.
func (c *FakePlans) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.Plan, err error) {
	emptyResult := &v1beta2.Plan{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(plansResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta2.Plan), err
}

// List takes label and field selectors, and returns the list of Plans that match those selectors.
func (c *FakePlans) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.PlanList, err error) {
	emptyResult := &v1beta2.PlanList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(plansResource, plansKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta2.PlanList{ListMeta: obj.(*v1beta2.PlanList).ListMeta}
	for _, item := range obj.(*v1beta2.PlanList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested plans.
func (c *FakePlans) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(plansResource, opts))
}

// Create takes the representation of a plan and creates it.  Returns the server's representation of the plan, and an error, if there is any.
func (c *FakePlans) Create(ctx context.Context, plan *v1beta2.Plan, opts v1.CreateOptions) (result *v1beta2.Plan, err error) {
	emptyResult := &v1beta2.Plan{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(plansResource, plan, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta2.Plan), err
}

// Update takes the representation of a plan and updates it. Returns the server's representation of the plan, and an error, if there is any.
func (c *FakePlans) Update(ctx context.Context, plan *v1beta2.Plan, opts v1.UpdateOptions) (result *v1beta2.Plan, err error) {
	emptyResult := &v1beta2.Plan{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(plansResource, plan, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta2.Plan), err
}

// Delete takes name of the plan and deletes it. Returns an error if one occurs.
func (c *FakePlans) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(plansResource, name, opts), &v1beta2.Plan{})
	return err
}
