/*
Copyright k0s authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta2 "github.com/k0sproject/k0s/pkg/apis/autopilot/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeControlNodes implements ControlNodeInterface
type FakeControlNodes struct {
	Fake *FakeAutopilotV1beta2
}

var controlnodesResource = v1beta2.SchemeGroupVersion.WithResource("controlnodes")

var controlnodesKind = v1beta2.SchemeGroupVersion.WithKind("ControlNode")

// Get takes name of the controlNode, and returns the corresponding controlNode object, and an error if there is any.
func (c *FakeControlNodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.ControlNode, err error) {
	emptyResult := &v1beta2.ControlNode{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(controlnodesResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta2.ControlNode), err
}

// List takes label and field selectors, and returns the list of ControlNodes that match those selectors.
func (c *FakeControlNodes) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.ControlNodeList, err error) {
	emptyResult := &v1beta2.ControlNodeList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(controlnodesResource, controlnodesKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta2.ControlNodeList{ListMeta: obj.(*v1beta2.ControlNodeList).ListMeta}
	for _, item := range obj.(*v1beta2.ControlNodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested controlNodes.
func (c *FakeControlNodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(controlnodesResource, opts))
}

// Create takes the representation of a controlNode and creates it.  Returns the server's representation of the controlNode, and an error, if there is any.
func (c *FakeControlNodes) Create(ctx context.Context, controlNode *v1beta2.ControlNode, opts v1.CreateOptions) (result *v1beta2.ControlNode, err error) {
	emptyResult := &v1beta2.ControlNode{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(controlnodesResource, controlNode, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta2.ControlNode), err
}

// Update takes the representation of a controlNode and updates it. Returns the server's representation of the controlNode, and an error, if there is any.
func (c *FakeControlNodes) Update(ctx context.Context, controlNode *v1beta2.ControlNode, opts v1.UpdateOptions) (result *v1beta2.ControlNode, err error) {
	emptyResult := &v1beta2.ControlNode{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(controlnodesResource, controlNode, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta2.ControlNode), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeControlNodes) UpdateStatus(ctx context.Context, controlNode *v1beta2.ControlNode, opts v1.UpdateOptions) (result *v1beta2.ControlNode, err error) {
	emptyResult := &v1beta2.ControlNode{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(controlnodesResource, "status", controlNode, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta2.ControlNode), err
}

// Delete takes name of the controlNode and deletes it. Returns an error if one occurs.
func (c *FakeControlNodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(controlnodesResource, name, opts), &v1beta2.ControlNode{})
	return err
}
