smoketests := \
	check-addons \
	check-basic \
	check-byocri \
	check-calico \
	check-cnichange \
	check-ctr \
	check-customports \
	check-dualstack \
	check-hacontrolplane \
	check-install \
	check-kine \
	check-multicontroller \
	check-singlenode \
	check-backup \
	check-airgap

