name: Pull request
about: Create a Pull Request
body:
  - type: textarea
    label: Issue/PR references
    placeholder: |
      Fixes #<issue number>
      Closes #<PR number> (alternative)

  - type: textarea
    label: What this PR includes
    description: A short description of what this PR does
    placeholder: |
      **Before:**
        ...

      **After:**
        ...
