// SPDX-FileCopyrightText: 2026 k0s authors
// SPDX-License-Identifier: Apache-2.0

// Package schemagen derives JSON Schemas from the CRDs embedded in k0s.
package schemagen

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"maps"
	"math"
	"path"
	"slices"
	"strconv"
	"strings"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/yaml"

	"github.com/k0sproject/k0s/static"
)

// Identifier identifies a versioned Kubernetes resource schema.
type Identifier struct {
	APIVersion string
	Kind       string
}

func (id Identifier) String() string {
	return id.APIVersion + " " + id.Kind
}

// List returns the schemas embedded in k0s, ordered by API version and kind.
func List() ([]Identifier, error) {
	crds, err := crds()
	if err != nil {
		return nil, err
	}
	var ids []Identifier
	for _, crd := range crds {
		for _, version := range crd.Spec.Versions {
			if version.Schema == nil || version.Schema.OpenAPIV3Schema == nil {
				continue
			}
			ids = append(ids, Identifier{APIVersion: crd.Spec.Group + "/" + version.Name, Kind: crd.Spec.Names.Kind})
		}
	}
	slices.SortFunc(ids, func(a, b Identifier) int {
		if a.APIVersion == b.APIVersion {
			return strings.Compare(a.Kind, b.Kind)
		}
		return strings.Compare(a.APIVersion, b.APIVersion)
	})
	return ids, nil
}

// Generate returns the draft-07 schema for apiVersion and kind.
func Generate(apiVersion, kind string) ([]byte, error) {
	crds, err := crds()
	if err != nil {
		return nil, err
	}
	for _, crd := range crds {
		if crd.Spec.Names.Kind != kind {
			continue
		}
		for _, version := range crd.Spec.Versions {
			if crd.Spec.Group+"/"+version.Name != apiVersion || version.Schema == nil || version.Schema.OpenAPIV3Schema == nil {
				continue
			}
			return generate(apiVersion, kind, version.Schema.OpenAPIV3Schema)
		}
	}
	return nil, fmt.Errorf("no schema for %s %s", apiVersion, kind)
}

func crds() ([]apiextensionsv1.CustomResourceDefinition, error) {
	var crds []apiextensionsv1.CustomResourceDefinition
	err := fs.WalkDir(static.CRDs, ".", func(name string, entry fs.DirEntry, err error) error {
		if err != nil || entry.IsDir() || path.Ext(name) != ".yaml" {
			return err
		}
		data, err := fs.ReadFile(static.CRDs, name)
		if err != nil {
			return err
		}
		var crd apiextensionsv1.CustomResourceDefinition
		if err := yaml.Unmarshal(data, &crd); err != nil {
			return fmt.Errorf("read CRD %q: %w", name, err)
		}
		crds = append(crds, crd)
		return nil
	})
	return crds, err
}

func generate(apiVersion, kind string, source *apiextensionsv1.JSONSchemaProps) ([]byte, error) {
	data, err := json.Marshal(source)
	if err != nil {
		return nil, err
	}
	var openAPI map[string]any
	if err := json.Unmarshal(data, &openAPI); err != nil {
		return nil, err
	}
	schema, err := structuralSchema(openAPI, false)
	if err != nil {
		return nil, err
	}
	schema["$schema"] = "http://json-schema.org/draft-07/schema#"
	schema["title"] = "k0s " + kind + " (" + apiVersion + ")"
	schema["$comment"] = "Generated by k0s docs json-schema. Do not edit this generated file directly. Use k0s config validate for additional semantic validation."
	data, err = json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

// structuralSchema translates the OpenAPI features used by k0s CRDs to JSON
// Schema draft-07. Reject unsupported features rather than silently changing
// validation semantics when a CRD evolves. Patterns must use the portable
// regular-expression subset described by JSON Schema draft-07 section 4.3.
func structuralSchema(source map[string]any, openObject bool) (map[string]any, error) {
	schema := maps.Clone(source)
	preserveUnknown, _ := source["x-kubernetes-preserve-unknown-fields"].(bool)
	if source["type"] == "object" && !openObject && !preserveUnknown {
		if _, ok := source["additionalProperties"]; !ok {
			schema["additionalProperties"] = false
		}
	}
	for key := range source {
		switch key {
		case "default", "description", "enum", "maxItems", "maxLength", "maximum",
			"minItems", "minLength", "minimum", "pattern", "required", "type":
		case "format":
			switch source[key] {
			case "date-time":
				if source["type"] != "string" {
					return nil, fmt.Errorf("unsupported format %v for type %v", source[key], source["type"])
				}
			case "int32":
				if source["type"] != "integer" {
					return nil, fmt.Errorf("unsupported format %v for type %v", source[key], source["type"])
				}
				if minimum, ok := source["minimum"].(float64); !ok || minimum < math.MinInt32 {
					schema["minimum"] = float64(math.MinInt32)
				}
				if maximum, ok := source["maximum"].(float64); !ok || maximum > math.MaxInt32 {
					schema["maximum"] = float64(math.MaxInt32)
				}
			case "int64":
				if source["type"] != "integer" {
					return nil, fmt.Errorf("unsupported format %v for type %v", source[key], source["type"])
				}
				if _, ok := source["minimum"]; !ok {
					schema["minimum"] = json.Number(strconv.FormatInt(math.MinInt64, 10))
				}
				if _, ok := source["maximum"]; !ok {
					schema["maximum"] = json.Number(strconv.FormatInt(math.MaxInt64, 10))
				}
			default:
				return nil, fmt.Errorf("unsupported format %v for type %v", source[key], source["type"])
			}
		case "x-kubernetes-int-or-string":
			if source[key] == true {
				schema["type"] = []any{"integer", "string"}
			}
			delete(schema, key)
		case "x-kubernetes-list-type", "x-kubernetes-list-map-keys", "x-kubernetes-preserve-unknown-fields":
			delete(schema, key)
		case "properties":
			properties := source[key].(map[string]any)
			converted := make(map[string]any, len(properties))
			for name, property := range properties {
				child, err := structuralSchema(property.(map[string]any), openObject || name == "metadata")
				if err != nil {
					return nil, fmt.Errorf("property %q: %w", name, err)
				}
				converted[name] = child
			}
			schema[key] = converted
		case "items", "additionalProperties":
			if child, ok := source[key].(map[string]any); ok {
				converted, err := structuralSchema(child, false)
				if err != nil {
					return nil, fmt.Errorf("%s: %w", key, err)
				}
				schema[key] = converted
			}
		default:
			return nil, fmt.Errorf("unsupported schema keyword %q", key)
		}
	}
	return schema, nil
}
