/*
Copyright 2021 Mirantis
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta2 "github.com/k0sproject/autopilot/pkg/apis/autopilot.k0sproject.io/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// FakePlanLists implements PlanListInterface
type FakePlanLists struct {
	Fake *FakeAutopilotV1beta2
}

var planlistsResource = schema.GroupVersionResource{Group: "autopilot.k0sproject.io", Version: "v1beta2", Resource: "planlists"}

var planlistsKind = schema.GroupVersionKind{Group: "autopilot.k0sproject.io", Version: "v1beta2", Kind: "PlanList"}

// Create takes the representation of a planList and creates it.  Returns the server's representation of the planList, and an error, if there is any.
func (c *FakePlanLists) Create(ctx context.Context, planList *v1beta2.PlanList, opts v1.CreateOptions) (result *v1beta2.PlanList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(planlistsResource, planList), &v1beta2.PlanList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.PlanList), err
}
