/*
Copyright 2021 Mirantis
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "github.com/k0sproject/autopilot/pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/typed/autopilot.k0sproject.io/v1beta2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAutopilotV1beta2 struct {
	*testing.Fake
}

func (c *FakeAutopilotV1beta2) ControlNodes() v1beta2.ControlNodeInterface {
	return &FakeControlNodes{c}
}

func (c *FakeAutopilotV1beta2) ControlNodeLists() v1beta2.ControlNodeListInterface {
	return &FakeControlNodeLists{c}
}

func (c *FakeAutopilotV1beta2) Plans() v1beta2.PlanInterface {
	return &FakePlans{c}
}

func (c *FakeAutopilotV1beta2) PlanLists() v1beta2.PlanListInterface {
	return &FakePlanLists{c}
}

func (c *FakeAutopilotV1beta2) UpdateConfigs() v1beta2.UpdateConfigInterface {
	return &FakeUpdateConfigs{c}
}

func (c *FakeAutopilotV1beta2) UpdateConfigLists() v1beta2.UpdateConfigListInterface {
	return &FakeUpdateConfigLists{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAutopilotV1beta2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
