/*
Copyright k0s authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/k0sproject/k0s/pkg/apis/etcd/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEtcdMembers implements EtcdMemberInterface
type FakeEtcdMembers struct {
	Fake *FakeEtcdV1beta1
}

var etcdmembersResource = v1beta1.SchemeGroupVersion.WithResource("etcdmembers")

var etcdmembersKind = v1beta1.SchemeGroupVersion.WithKind("EtcdMember")

// Get takes name of the etcdMember, and returns the corresponding etcdMember object, and an error if there is any.
func (c *FakeEtcdMembers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.EtcdMember, err error) {
	emptyResult := &v1beta1.EtcdMember{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(etcdmembersResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.EtcdMember), err
}

// List takes label and field selectors, and returns the list of EtcdMembers that match those selectors.
func (c *FakeEtcdMembers) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.EtcdMemberList, err error) {
	emptyResult := &v1beta1.EtcdMemberList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(etcdmembersResource, etcdmembersKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.EtcdMemberList{ListMeta: obj.(*v1beta1.EtcdMemberList).ListMeta}
	for _, item := range obj.(*v1beta1.EtcdMemberList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested etcdMembers.
func (c *FakeEtcdMembers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(etcdmembersResource, opts))
}

// Create takes the representation of a etcdMember and creates it.  Returns the server's representation of the etcdMember, and an error, if there is any.
func (c *FakeEtcdMembers) Create(ctx context.Context, etcdMember *v1beta1.EtcdMember, opts v1.CreateOptions) (result *v1beta1.EtcdMember, err error) {
	emptyResult := &v1beta1.EtcdMember{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(etcdmembersResource, etcdMember, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.EtcdMember), err
}

// Update takes the representation of a etcdMember and updates it. Returns the server's representation of the etcdMember, and an error, if there is any.
func (c *FakeEtcdMembers) Update(ctx context.Context, etcdMember *v1beta1.EtcdMember, opts v1.UpdateOptions) (result *v1beta1.EtcdMember, err error) {
	emptyResult := &v1beta1.EtcdMember{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(etcdmembersResource, etcdMember, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.EtcdMember), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEtcdMembers) UpdateStatus(ctx context.Context, etcdMember *v1beta1.EtcdMember, opts v1.UpdateOptions) (result *v1beta1.EtcdMember, err error) {
	emptyResult := &v1beta1.EtcdMember{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(etcdmembersResource, "status", etcdMember, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.EtcdMember), err
}

// Delete takes name of the etcdMember and deletes it. Returns an error if one occurs.
func (c *FakeEtcdMembers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(etcdmembersResource, name, opts), &v1beta1.EtcdMember{})
	return err
}

// Patch applies the patch and returns the patched etcdMember.
func (c *FakeEtcdMembers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.EtcdMember, err error) {
	emptyResult := &v1beta1.EtcdMember{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(etcdmembersResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.EtcdMember), err
}
