#!/bin/sh

: ${bindata:=bindata}
: ${gooffsets:=bindata-offsets.go}
: ${pkg:=assets}

offset=0
rm -f "$bindata" "$gooffsets"

( cat <<HEADER
// Code generated by $0
// DO NOT EDIT!

package $pkg

var (
	Offsets = map[string]int64 {
HEADER

for f; do
	size=$(stat -c "%s" $f)
	printf '\t\t"%s": %d,\n' "${f#$prefix}" $offset
	cat $f >> $bindata
	offset=$(($offset + $size))
done

cat <<FOOTER
	}

	BinDataSize int64 = $offset
)

FOOTER
) | gofmt > "$gooffsets"
