// SPDX-FileCopyrightText: 2026 k0s authors
// SPDX-License-Identifier: Apache-2.0

// config-schema derives an editor schema from the generated ClusterConfig CRD.
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"slices"
	"strings"

	"sigs.k8s.io/yaml"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: config-schema <clusterconfig-crd.yaml>")
		os.Exit(1)
	}
	data, err := os.ReadFile(os.Args[1])
	if err == nil {
		data, err = generate(data)
	}
	if err == nil {
		_, err = os.Stdout.Write(data)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(data []byte) ([]byte, error) {
	var crd struct {
		Spec struct {
			Versions []struct {
				Name   string
				Schema struct {
					OpenAPIV3Schema map[string]any
				}
			}
		}
	}
	if err := yaml.Unmarshal(data, &crd); err != nil {
		return nil, fmt.Errorf("read ClusterConfig CRD: %w", err)
	}
	for _, version := range crd.Spec.Versions {
		if version.Name != "v1beta1" || version.Schema.OpenAPIV3Schema == nil {
			continue
		}
		schema := structuralSchema(version.Schema.OpenAPIV3Schema, "", false)
		schema["$schema"] = "http://json-schema.org/draft-07/schema#"
		schema["title"] = "k0s ClusterConfig (k0s.k0sproject.io/v1beta1)"
		schema["$comment"] = "Generated by make config-schema. Do not edit this generated file directly. Use k0s config validate for additional semantic validation."
		data, err := json.MarshalIndent(schema, "", "  ")
		if err != nil {
			return nil, err
		}
		return append(data, '\n'), nil
	}
	return nil, errors.New("ClusterConfig CRD has no v1beta1 schema")
}

// Keep portable CRD constraints, with exceptions for config-file defaulting.
// Omit patterns (which can use Go-specific syntax), OpenAPI formats, and defaults
// (which do not always match config-file defaults). Paths use / separators and
// [] for array items. Optional fields may be null; required fields and list
// entries must supply a value.
func structuralSchema(source map[string]any, path string, nullable bool) map[string]any {
	schema := make(map[string]any)
	for _, key := range []string{"description", "required", "enum", "minimum", "maximum", "minLength", "maxLength", "minItems", "maxItems"} {
		if value, ok := source[key]; ok {
			schema[key] = value
		}
	}
	configFileConstraints(schema, path)
	if typ, ok := source["type"].(string); ok {
		schema["type"] = typ
		if nullable {
			schema["type"] = []string{typ, "null"}
		}
	}
	// Helm timeouts also accept the legacy integer duration in nanoseconds.
	if source["x-kubernetes-int-or-string"] == true {
		types := []string{"integer", "string"}
		if nullable {
			types = append(types, "null")
		}
		schema["type"] = types
	}
	if values, ok := schema["enum"].([]any); ok && nullable {
		schema["enum"] = append(slices.Clone(values), nil)
	}
	if properties, ok := source["properties"].(map[string]any); ok {
		converted := make(map[string]any, len(properties))
		required, _ := schema["required"].([]any)
		for name, property := range properties {
			converted[name] = structuralSchema(property.(map[string]any), path+"/"+name, !slices.Contains(required, any(name)))
		}
		schema["properties"] = converted
		// Objects with no declared properties (metadata and RawExtension) stay
		// open. Reject unknown fields elsewhere for editor typo detection, even
		// where a nested config decoder would silently ignore them.
		schema["additionalProperties"] = source["x-kubernetes-preserve-unknown-fields"] == true
	}
	if child, ok := source["items"].(map[string]any); ok {
		schema["items"] = structuralSchema(child, path+"[]", false)
	}
	if child, ok := source["additionalProperties"].(map[string]any); ok {
		schema["additionalProperties"] = structuralSchema(child, path+"/*", true)
	}
	return schema
}

// These exceptions follow the configuration types' defaulting and validation,
// rather than assuming that every CRD default permits an empty config value.
func configFileConstraints(schema map[string]any, path string) {
	if strings.HasPrefix(path, "/spec/images/") {
		// ClusterImages starts with defaults, so image and version overrides
		// can be supplied independently.
		delete(schema, "required")
	}
	switch path {
	case "/spec/network/nodeLocalLoadBalancing/envoyProxy/image",
		"/spec/network/nodeLocalLoadBalancing/traefik/image":
		delete(schema, "required")
	case "/spec/network/nodeLocalLoadBalancing/envoyProxy/image/image",
		"/spec/network/nodeLocalLoadBalancing/traefik/image/image":
		// Both proxy setDefaults methods also replace empty image names.
		delete(schema, "minLength")
	case "/spec/featureGates[]":
		// An omitted enabled flag means false; only the name is needed.
		schema["required"] = []any{"name"}
	case "/spec/featureGates[]/components":
		// An empty component list selects the default components.
		delete(schema, "minItems")
	case "/spec/api/port", "/spec/api/k0sApiPort",
		"/spec/network/controlPlaneLoadBalancing/keepalived/userSpaceProxyBindPort",
		"/spec/network/controlPlaneLoadBalancing/keepalived/virtualServers[]/persistenceTimeoutSeconds",
		"/spec/network/controlPlaneLoadBalancing/keepalived/vrrpInstances[]/virtualRouterID",
		"/spec/network/controlPlaneLoadBalancing/keepalived/vrrpInstances[]/advertIntervalSeconds",
		"/spec/network/nodeLocalLoadBalancing/envoyProxy/apiServerBindPort",
		"/spec/network/nodeLocalLoadBalancing/traefik/apiServerBindPort":
		// Zero requests a default. Konnectivity ports do not share this rule.
		schema["minimum"] = 0
	case "/spec/images/default_pull_policy",
		"/spec/network/primaryAddressFamily", "/spec/network/kuberouter/hairpin",
		"/spec/network/controlPlaneLoadBalancing/type",
		"/spec/network/controlPlaneLoadBalancing/keepalived/virtualServers[]/lbAlgo",
		"/spec/network/controlPlaneLoadBalancing/keepalived/virtualServers[]/lbKind",
		"/spec/network/nodeLocalLoadBalancing/type",
		"/spec/network/nodeLocalLoadBalancing/envoyProxy/imagePullPolicy",
		"/spec/network/nodeLocalLoadBalancing/traefik/imagePullPolicy":
		// Empty strings request a default or preserve legacy behavior.
		schema["enum"] = append(slices.Clone(schema["enum"].([]any)), "")
	}
}
