// SPDX-FileCopyrightText: 2026 k0s authors
// SPDX-License-Identifier: Apache-2.0

// config-schema derives an editor schema from the generated ClusterConfig CRD.
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"math"
	"os"

	"sigs.k8s.io/yaml"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: config-schema <clusterconfig-crd.yaml>")
		os.Exit(1)
	}
	data, err := os.ReadFile(os.Args[1])
	if err == nil {
		data, err = generate(data)
	}
	if err == nil {
		_, err = os.Stdout.Write(data)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(data []byte) ([]byte, error) {
	var crd struct {
		Spec struct {
			Versions []struct {
				Name   string
				Schema struct {
					OpenAPIV3Schema map[string]any
				}
			}
		}
	}
	if err := yaml.Unmarshal(data, &crd); err != nil {
		return nil, fmt.Errorf("read ClusterConfig CRD: %w", err)
	}
	for _, version := range crd.Spec.Versions {
		if version.Name != "v1beta1" || version.Schema.OpenAPIV3Schema == nil {
			continue
		}
		schema, err := structuralSchema(version.Schema.OpenAPIV3Schema)
		if err != nil {
			return nil, err
		}
		schema["$schema"] = "http://json-schema.org/draft-07/schema#"
		schema["title"] = "k0s ClusterConfig (k0s.k0sproject.io/v1beta1)"
		schema["$comment"] = "Generated by make config-schema. Do not edit this generated file directly. Use k0s config validate for additional semantic validation."
		data, err := json.MarshalIndent(schema, "", "  ")
		if err != nil {
			return nil, err
		}
		return append(data, '\n'), nil
	}
	return nil, errors.New("ClusterConfig CRD has no v1beta1 schema")
}

// structuralSchema translates the OpenAPI features used by the ClusterConfig CRD
// to JSON Schema draft-07. Reject unsupported features rather than silently
// changing their validation semantics when the CRD evolves.
func structuralSchema(source map[string]any) (map[string]any, error) {
	schema := maps.Clone(source)
	for key := range source {
		switch key {
		case "default", "description", "enum", "maxItems", "maxLength", "maximum",
			"minItems", "minLength", "minimum", "pattern", "required", "type":
			// These keywords have the same meaning in both dialects.
		case "format":
			if source[key] != "int32" || source["type"] != "integer" {
				return nil, fmt.Errorf("unsupported format %v for type %v", source[key], source["type"])
			}
			// JSON Schema does not enforce OpenAPI's numeric formats.
			if minimum, ok := source["minimum"].(float64); !ok || minimum < math.MinInt32 {
				schema["minimum"] = float64(math.MinInt32)
			}
			if maximum, ok := source["maximum"].(float64); !ok || maximum > math.MaxInt32 {
				schema["maximum"] = float64(math.MaxInt32)
			}
		case "x-kubernetes-int-or-string":
			if source[key] == true {
				schema["type"] = []any{"integer", "string"}
			}
			delete(schema, key)
		case "x-kubernetes-list-type", "x-kubernetes-list-map-keys", "x-kubernetes-preserve-unknown-fields":
			// Kubernetes list and pruning behavior has no draft-07 equivalent.
			delete(schema, key)
		case "properties":
			properties := source[key].(map[string]any)
			converted := make(map[string]any, len(properties))
			for name, property := range properties {
				child, err := structuralSchema(property.(map[string]any))
				if err != nil {
					return nil, fmt.Errorf("property %q: %w", name, err)
				}
				converted[name] = child
			}
			schema[key] = converted
		case "items", "additionalProperties":
			if child, ok := source[key].(map[string]any); ok {
				converted, err := structuralSchema(child)
				if err != nil {
					return nil, fmt.Errorf("%s: %w", key, err)
				}
				schema[key] = converted
			}
		default:
			return nil, fmt.Errorf("unsupported schema keyword %q", key)
		}
	}
	return schema, nil
}
