// SPDX-FileCopyrightText: k0s authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

type ControlNodeExpansion interface{}

type PlanExpansion interface{}

type UpdateConfigExpansion interface{}
