// SPDX-FileCopyrightText: k0s authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	context "context"

	autopilotv1beta2 "github.com/k0sproject/k0s/pkg/apis/autopilot/v1beta2"
	scheme "github.com/k0sproject/k0s/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PlansGetter has a method to return a PlanInterface.
// A group's client should implement this interface.
type PlansGetter interface {
	Plans() PlanInterface
}

// PlanInterface has methods to work with Plan resources.
type PlanInterface interface {
	Create(ctx context.Context, plan *autopilotv1beta2.Plan, opts v1.CreateOptions) (*autopilotv1beta2.Plan, error)
	Update(ctx context.Context, plan *autopilotv1beta2.Plan, opts v1.UpdateOptions) (*autopilotv1beta2.Plan, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, plan *autopilotv1beta2.Plan, opts v1.UpdateOptions) (*autopilotv1beta2.Plan, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*autopilotv1beta2.Plan, error)
	List(ctx context.Context, opts v1.ListOptions) (*autopilotv1beta2.PlanList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *autopilotv1beta2.Plan, err error)
	PlanExpansion
}

// plans implements PlanInterface
type plans struct {
	*gentype.ClientWithList[*autopilotv1beta2.Plan, *autopilotv1beta2.PlanList]
}

// newPlans returns a Plans
func newPlans(c *AutopilotV1beta2Client) *plans {
	return &plans{
		gentype.NewClientWithList[*autopilotv1beta2.Plan, *autopilotv1beta2.PlanList](
			"plans",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *autopilotv1beta2.Plan { return &autopilotv1beta2.Plan{} },
			func() *autopilotv1beta2.PlanList { return &autopilotv1beta2.PlanList{} },
		),
	}
}
