name: Bug report
description: Create a report to help us improve
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please use this template while reporting a bug and provide as much info as possible.
        Not doing so may result in your bug not being addressed in a timely manner. Thanks!

  - type: checkboxes
    attributes:
      label: "Before creating an issue, make sure you've checked the following:"
      options:
        - label: You are running the latest released version of k0s
          required: true
        - label: Make sure you've searched for existing issues, both open and closed
          required: true
        - label: Make sure you've searched for PRs too, a fix might've been merged already
          required: true
        - label: You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.
          required: true

  # Should actually be included in `k0s sysinfo` or something like `k0s version --full`
  - type: textarea
    attributes:
      label: Platform
      description: >-
        Which platform did you run k0s on?
        Use: `uname -srvmo; cat /etc/os-release || lsb_release -a`
      render: shell

  - type: input
    attributes:
      label: Version
      description: "Use: `k0s version`"

  - type: textarea
    attributes:
      label: Sysinfo
      description: "Use: `k0s sysinfo`"
      value: |
        <details><summary>`k0s sysinfo`</summary>
        <pre>
        ➡️ Please replace this text with the output of `k0s sysinfo`. ⬅️
        </pre>
        </details>

  - type: textarea
    attributes:
      label: What happened?
      description: A clear and concise description of the bug

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue? (as minimally and as precisely as possible)
      value: |
        1.
        2.
        3.

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen

  - type: textarea
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened

  - type: textarea
    attributes:
      label: Screenshots and logs
      description: |
        If applicable, add screenshots to help explain your problem.
        Also add any output from kubectl if applicable.
        Use: `k0s kubectl logs`

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here
