name: Feature suggestion
description: Suggest an idea for this project
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when ...

  - type: textarea
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to happen.
      placeholder: It would be awesome if ...

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
