---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-windows-config
  namespace: kube-system
data:
  config: |
    {
      "name": "Calico",
      "cniVersion": "0.3.1",
      "plugins\": [
        { 
          "DNS": {
              "Nameservers":["10.96.0.10"],
              "Search":["svc.cluster.local"]
          },
          "capabilities":{"dns":true},
          "datastore_type": "kubernetes",
          "ipam":{
            "subnet": "usePodCidr",
            "type": "calico-ipam"
          },
          "kubernetes":{
            "kubeconfig":"c:/etc/cni/net.d/calico-kubeconfig"
          },
          "log_file_max_age":30,
          "log_file_max_count":10,
          "log_file_max_size":100,
          "log_file_path": "c:/var/log/calico/cni/cni.log",
          "log_level":"Info",
          "mode": "vxlan",
          "mtu":0,
          "name":"Calico",
          "nodename":"__KUBERNETES_NODE_NAME__",
          "nodename_file":"__NODENAME_FILE__",
          "nodename_file_optional":true,
          "policies":[
            {
              "Name":"EndpointPolicy",
              "Value":{
                "ExceptionList":["10.96.0.0/12"],
                "Type":"OutBoundNAT"}
              },
              {
                "Name":"EndpointPolicy",
                "Value":{
                  "DestinationPrefix":"10.96.0.0/12",
                  "NeedEncap":true,
                  "Type":"SDNROUTE"
                }
            }
          ],
          "policy":{
            "type":"k8s"
          },
          "type":"calico",
          "vxlan_mac_prefix":"0E-2A",
          "vxlan_vni":4096,
          "windows_loopback_DSR":"__DSR_SUPPORT__",
          "windows_use_single_network":true
        }
      ]
    }
  