ARG VERSION_CONTROLLERGEN=v0.8.0
ARG VERSION_CLIENTGEN=v0.23.3

FROM golang:1.18.1-alpine AS build-base
RUN apk add build-base

FROM build-base AS build-clientgen
ARG VERSION_CLIENTGEN
RUN go install k8s.io/code-generator/cmd/client-gen@${VERSION_CLIENTGEN}

FROM build-base AS build-controllergen
ARG VERSION_CONTROLLERGEN
RUN go install sigs.k8s.io/controller-tools/cmd/controller-gen@${VERSION_CONTROLLERGEN}

FROM build-base
COPY --from=build-clientgen /go/bin/client-gen /go/bin
COPY --from=build-controllergen /go/bin/controller-gen /go/bin
RUN mkdir -p /.cache/go-build
RUN chmod -R 777 /go /.cache
WORKDIR /go/src/autopilot
