---
{{ if and .IncludeWindows (eq .Mode "vxlan") -}}
apiVersion: crd.projectcalico.org/v1
kind: IPAMConfig
metadata:
  name: default
spec:
  strictAffinity: true
  autoAllocateBlocks: true
{{ end -}}
