#!/bin/sh
K0SCTL_PATH=/opt/k0sctl
K0S_PATH=/opt/k0s
K0SCTL_CONFIG=/root/k0sctl.yaml

# This file is generated by cloud init
sh /opt/fetchk0s.sh

# populate k0s config
cat <<EOF > ${K0SCTL_CONFIG}
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - role: controller+worker
    ssh:
      # By using the ip address we skip registering the host in the DNS saving some time.
      address: $(hostname -I | cut -d' ' -f1)
      user: root
      keyPath: ~/.ssh/id_rsa
    k0sBinaryPath: ${K0S_PATH}
    uploadBinary: true
EOF

# cloud-init doesn't define HOME by default, but k0sctl requires it.
export HOME=/root

${K0SCTL_PATH} apply --config ${K0SCTL_CONFIG} > /var/log/k0sctl-install.log
cp ${K0SCTL_PATH} ${K0S_PATH} /bin


date >> /var/log/k0sctl-install.log
