/*
Copyright 2020 k0s authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package token

import (
	"context"
	"fmt"
	"time"

	"github.com/sirupsen/logrus"
	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"

	"github.com/k0sproject/k0s/internal/pkg/random"
	k8sutil "github.com/k0sproject/k0s/pkg/kubernetes"
)

type Token struct {
	ID     string
	Role   string
	Expiry string
}

func (t Token) ToArray() []string {
	return []string{t.ID, t.Role, t.Expiry}
}

// NewManager creates a new token manager using given kubeconfig
func NewManager(kubeconfig string) (*Manager, error) {
	logrus.Debugf("loading kubeconfig from: %s", kubeconfig)
	client, err := k8sutil.NewClientFromFile(kubeconfig)
	if err != nil {
		return nil, err
	}
	return &Manager{
		client: client,
	}, nil
}

// NewManagerForClient creates a new token manager using given client
func NewManagerForClient(client kubernetes.Interface) (*Manager, error) {
	return &Manager{
		client: client,
	}, nil
}

// Manager is responsible to manage the join tokens in kube API as secrets in kube-system namespace
type Manager struct {
	client kubernetes.Interface
}

// Create creates a new bootstrap token
func (m *Manager) Create(ctx context.Context, valid time.Duration, role string) (string, error) {
	tokenID := random.String(6)
	tokenSecret := random.String(16)

	token := fmt.Sprintf("%s.%s", tokenID, tokenSecret)

	data := make(map[string]string)
	data["token-id"] = tokenID
	data["token-secret"] = tokenSecret
	if valid != 0 {
		data["expiration"] = time.Now().Add(valid).UTC().Format(time.RFC3339)
		logrus.Debugf("Set expiry to %s", data["expiration"])
	}

	// This "usage-" is shared for both roles of the token
	// which allows both roles execute calls to the k0s api.
	// this is done because we need to call k0s api from
	// windows workers during the join step
	data["usage-bootstrap-api-auth"] = "true"

	if role == "worker" {
		data["description"] = "Worker bootstrap token generated by k0s"
		data["usage-bootstrap-authentication"] = "true"
		data["usage-bootstrap-api-worker-calls"] = "true"
	} else {
		data["description"] = "Controller bootstrap token generated by k0s"
		data["usage-bootstrap-authentication"] = "false"
		data["usage-bootstrap-signing"] = "false"
		data["usage-controller-join"] = "true"
	}

	secret := &v1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      fmt.Sprintf("bootstrap-token-%s", tokenID),
			Namespace: "kube-system",
		},
		Type:       v1.SecretTypeBootstrapToken,
		StringData: data,
	}

	_, err := m.client.CoreV1().Secrets("kube-system").Create(ctx, secret, metav1.CreateOptions{})
	if err != nil {
		return "", err
	}

	return token, nil
}

// List returns all the join tokens for given role. If role == "" then it returns all join tokens
func (m *Manager) List(ctx context.Context, role string) ([]Token, error) {
	tokenList, err := m.client.CoreV1().Secrets("kube-system").List(ctx, metav1.ListOptions{
		FieldSelector: "type=bootstrap.kubernetes.io/token",
	})
	if err != nil {
		return nil, err
	}
	tokens := make([]Token, 0, len(tokenList.Items))

	for _, t := range tokenList.Items {
		r := "worker"
		if string(t.Data["usage-controller-join"]) == "true" {
			r = "controller"
		}
		if r == role || role == "" {
			tokens = append(tokens, Token{
				ID:     string(t.Data["token-id"]),
				Role:   r,
				Expiry: string(t.Data["expiration"]),
			})
		}
	}
	return tokens, nil
}

func (m *Manager) Remove(ctx context.Context, tokenID string) error {
	err := m.client.CoreV1().Secrets("kube-system").Delete(ctx, fmt.Sprintf("bootstrap-token-%s", tokenID), metav1.DeleteOptions{})
	if errors.IsNotFound(err) {
		return nil
	}
	return err
}
