/*
Copyright 2021 Mirantis
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta2

type ControlNodeExpansion interface{}

type ControlNodeListExpansion interface{}

type PlanExpansion interface{}

type PlanListExpansion interface{}

type UpdateConfigExpansion interface{}

type UpdateConfigListExpansion interface{}
