//go:build !noembedbins
// Code generated by go generate; DO NOT EDIT.

// datafile: bindata_linux

package assets

var (
	BinData = map[string]struct{ offset, size, originalSize int64 }{
		"bin/containerd.gz": { 0, 15058110, 46255512},
		"bin/containerd-shim.gz": { 15058110, 2606547, 6881464},
		"bin/containerd-shim-runc-v2.gz": { 17664657, 3511046, 9830562},
		"bin/etcd.gz": { 21175703, 8903722, 25100450},
		"bin/keepalived.gz": { 30079425, 2900207, 5992896},
		"bin/kine.gz": { 32979632, 12390966, 36082928},
		"bin/konnectivity-server.gz": { 45370598, 13321561, 47972514},
		"bin/kube-apiserver.gz": { 58692159, 26413067, 94961826},
		"bin/kube-controller-manager.gz": { 85105226, 23682619, 86442146},
		"bin/kube-scheduler.gz": { 108787845, 18463006, 66257058},
		"bin/kubelet.gz": { 127250851, 21935933, 76677282},
		"bin/runc.gz": { 149186784, 4160912, 11690040},
		"bin/xtables-legacy-multi.gz": { 153347696, 254360, 697520},
		"bin/xtables-nft-multi.gz": { 153602056, 359573, 902744},
	}

	BinDataSize int64 = 153961629
)
