/*
Copyright k0s authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta2 "github.com/k0sproject/k0s/pkg/apis/autopilot.k0sproject.io/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// FakeUpdateConfigLists implements UpdateConfigListInterface
type FakeUpdateConfigLists struct {
	Fake *FakeAutopilotV1beta2
}

var updateconfiglistsResource = schema.GroupVersionResource{Group: "autopilot.k0sproject.io", Version: "v1beta2", Resource: "updateconfiglists"}

var updateconfiglistsKind = schema.GroupVersionKind{Group: "autopilot.k0sproject.io", Version: "v1beta2", Kind: "UpdateConfigList"}

// Create takes the representation of a updateConfigList and creates it.  Returns the server's representation of the updateConfigList, and an error, if there is any.
func (c *FakeUpdateConfigLists) Create(ctx context.Context, updateConfigList *v1beta2.UpdateConfigList, opts v1.CreateOptions) (result *v1beta2.UpdateConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(updateconfiglistsResource, updateConfigList), &v1beta2.UpdateConfigList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpdateConfigList), err
}
