// SPDX-FileCopyrightText: 2026 k0s authors
// SPDX-License-Identifier: Apache-2.0

package v1beta1

import (
	"k8s.io/apimachinery/pkg/util/validation/field"
)

// CoreDNS defines the configuration options for the CoreDNS component.
type CoreDNS struct {
	// Patches holds customizations applied to the CoreDNS resources generated by k0s before they applied.
	// +optional
	Patches Patches `json:"patches,omitempty"`
}

func (c *CoreDNS) Validate(path *field.Path) (errs []error) {
	if c == nil {
		return
	}
	errs = append(errs, c.Patches.validate(path.Child("patches"))...)
	return
}
