// SPDX-FileCopyrightText: 2026 k0s authors
// SPDX-License-Identifier: Apache-2.0

package v1beta1

import (
	"k8s.io/apimachinery/pkg/util/validation/field"
)

// MetricsServer defines the configuration options for the metrics-server
// component.
type MetricsServer struct {
	// Patches holds customizations applied to the metrics-server resources generated by k0s before they applied.
	// +optional
	Patches Patches `json:"patches,omitempty"`
}

func (m *MetricsServer) Validate(path *field.Path) (errs []error) {
	if m == nil {
		return
	}
	errs = append(errs, m.Patches.validate(path.Child("patches"))...)
	return
}
