/*
Copyright k0s authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	"context"

	v1beta2 "github.com/k0sproject/k0s/pkg/apis/autopilot.k0sproject.io/v1beta2"
	scheme "github.com/k0sproject/k0s/pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	rest "k8s.io/client-go/rest"
)

// PlanListsGetter has a method to return a PlanListInterface.
// A group's client should implement this interface.
type PlanListsGetter interface {
	PlanLists() PlanListInterface
}

// PlanListInterface has methods to work with PlanList resources.
type PlanListInterface interface {
	Create(ctx context.Context, planList *v1beta2.PlanList, opts v1.CreateOptions) (*v1beta2.PlanList, error)
	PlanListExpansion
}

// planLists implements PlanListInterface
type planLists struct {
	client rest.Interface
}

// newPlanLists returns a PlanLists
func newPlanLists(c *AutopilotV1beta2Client) *planLists {
	return &planLists{
		client: c.RESTClient(),
	}
}

// Create takes the representation of a planList and creates it.  Returns the server's representation of the planList, and an error, if there is any.
func (c *planLists) Create(ctx context.Context, planList *v1beta2.PlanList, opts v1.CreateOptions) (result *v1beta2.PlanList, err error) {
	result = &v1beta2.PlanList{}
	err = c.client.Post().
		Resource("planlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(planList).
		Do(ctx).
		Into(result)
	return
}
