/*
Copyright k0s authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	"context"
	"time"

	v1beta2 "github.com/k0sproject/k0s/pkg/apis/autopilot.k0sproject.io/v1beta2"
	scheme "github.com/k0sproject/k0s/pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PlansGetter has a method to return a PlanInterface.
// A group's client should implement this interface.
type PlansGetter interface {
	Plans() PlanInterface
}

// PlanInterface has methods to work with Plan resources.
type PlanInterface interface {
	Create(ctx context.Context, plan *v1beta2.Plan, opts v1.CreateOptions) (*v1beta2.Plan, error)
	Update(ctx context.Context, plan *v1beta2.Plan, opts v1.UpdateOptions) (*v1beta2.Plan, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta2.Plan, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta2.PlanList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	PlanExpansion
}

// plans implements PlanInterface
type plans struct {
	client rest.Interface
}

// newPlans returns a Plans
func newPlans(c *AutopilotV1beta2Client) *plans {
	return &plans{
		client: c.RESTClient(),
	}
}

// Get takes name of the plan, and returns the corresponding plan object, and an error if there is any.
func (c *plans) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.Plan, err error) {
	result = &v1beta2.Plan{}
	err = c.client.Get().
		Resource("plans").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Plans that match those selectors.
func (c *plans) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.PlanList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta2.PlanList{}
	err = c.client.Get().
		Resource("plans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested plans.
func (c *plans) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("plans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a plan and creates it.  Returns the server's representation of the plan, and an error, if there is any.
func (c *plans) Create(ctx context.Context, plan *v1beta2.Plan, opts v1.CreateOptions) (result *v1beta2.Plan, err error) {
	result = &v1beta2.Plan{}
	err = c.client.Post().
		Resource("plans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(plan).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a plan and updates it. Returns the server's representation of the plan, and an error, if there is any.
func (c *plans) Update(ctx context.Context, plan *v1beta2.Plan, opts v1.UpdateOptions) (result *v1beta2.Plan, err error) {
	result = &v1beta2.Plan{}
	err = c.client.Put().
		Resource("plans").
		Name(plan.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(plan).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the plan and deletes it. Returns an error if one occurs.
func (c *plans) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("plans").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}
