/*
Copyright k0s authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "github.com/k0sproject/k0s/pkg/apis/helm/v1beta1"
	scheme "github.com/k0sproject/k0s/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ChartsGetter has a method to return a ChartInterface.
// A group's client should implement this interface.
type ChartsGetter interface {
	Charts(namespace string) ChartInterface
}

// ChartInterface has methods to work with Chart resources.
type ChartInterface interface {
	Create(ctx context.Context, chart *v1beta1.Chart, opts v1.CreateOptions) (*v1beta1.Chart, error)
	Update(ctx context.Context, chart *v1beta1.Chart, opts v1.UpdateOptions) (*v1beta1.Chart, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.Chart, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ChartList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	ChartExpansion
}

// charts implements ChartInterface
type charts struct {
	*gentype.ClientWithList[*v1beta1.Chart, *v1beta1.ChartList]
}

// newCharts returns a Charts
func newCharts(c *HelmV1beta1Client, namespace string) *charts {
	return &charts{
		gentype.NewClientWithList[*v1beta1.Chart, *v1beta1.ChartList](
			"charts",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.Chart { return &v1beta1.Chart{} },
			func() *v1beta1.ChartList { return &v1beta1.ChartList{} }),
	}
}
