// SPDX-FileCopyrightText: k0s authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	http "net/http"

	helmv1beta1 "github.com/k0sproject/k0s/pkg/apis/helm/v1beta1"
	scheme "github.com/k0sproject/k0s/pkg/client/clientset/scheme"
	rest "k8s.io/client-go/rest"
)

type HelmV1beta1Interface interface {
	RESTClient() rest.Interface
	ChartsGetter
}

// HelmV1beta1Client is used to interact with features provided by the helm.k0sproject.io group.
type HelmV1beta1Client struct {
	restClient rest.Interface
}

func (c *HelmV1beta1Client) Charts(namespace string) ChartInterface {
	return newCharts(c, namespace)
}

// NewForConfig creates a new HelmV1beta1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*HelmV1beta1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new HelmV1beta1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*HelmV1beta1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &HelmV1beta1Client{client}, nil
}

// NewForConfigOrDie creates a new HelmV1beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *HelmV1beta1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new HelmV1beta1Client for the given RESTClient.
func New(c rest.Interface) *HelmV1beta1Client {
	return &HelmV1beta1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := helmv1beta1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *HelmV1beta1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
