// SPDX-FileCopyrightText: k0s authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/k0sproject/k0s/pkg/apis/helm/v1beta1"
	helmv1beta1 "github.com/k0sproject/k0s/pkg/client/clientset/typed/helm/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCharts implements ChartInterface
type fakeCharts struct {
	*gentype.FakeClientWithList[*v1beta1.Chart, *v1beta1.ChartList]
	Fake *FakeHelmV1beta1
}

func newFakeCharts(fake *FakeHelmV1beta1, namespace string) helmv1beta1.ChartInterface {
	return &fakeCharts{
		gentype.NewFakeClientWithList[*v1beta1.Chart, *v1beta1.ChartList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("charts"),
			v1beta1.SchemeGroupVersion.WithKind("Chart"),
			func() *v1beta1.Chart { return &v1beta1.Chart{} },
			func() *v1beta1.ChartList { return &v1beta1.ChartList{} },
			func(dst, src *v1beta1.ChartList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.ChartList) []*v1beta1.Chart { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.ChartList, items []*v1beta1.Chart) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
