ARG PYTHON_IMAGE_VERSION

FROM python:${PYTHON_IMAGE_VERSION} as builder

ARG KUBE_VERSION

# Prepare Python virtual env
ENV PYTHONUNBUFFERED 1
RUN \
  apk add --no-cache python3 \
  && python3 -m venv /mkdocs/venv

# Copy requirements.txt
COPY ./requirements_pip.txt ./requirements.txt /mkdocs/

# Install python dependencies
ENV VIRTUAL_ENV=/deps/venv PATH=/mkdocs/venv/bin:$PATH
RUN pip install --disable-pip-version-check -r /mkdocs/requirements_pip.txt \
  && pip --version \
  && pip install --disable-pip-version-check -r /mkdocs/requirements.txt

WORKDIR /k0s

# Expose MkDocs development server port
EXPOSE 8000

# Start development server by default
ENV KUBE_VERSION=${KUBE_VERSION}
ENTRYPOINT ["mkdocs"]
CMD ["serve", "--dev-addr=0.0.0.0:8000"]
