ARG PYTHON_IMAGE_VERSION

FROM python:${PYTHON_IMAGE_VERSION} as builder

# Prepare Python virtual env
ENV PYTHONUNBUFFERED 1
RUN \
  apk add --no-cache \
    git \
    pythonispython3 \
  && git config --global --add safe.directory /k0s \
  && python -m venv --upgrade-deps /mkdocs/venv

# Copy requirements.txt
COPY ./requirements.txt /mkdocs/requirements.txt

# Install python dependencies
ENV VIRTUAL_ENV=/deps/venv PATH=/mkdocs/venv/bin:$PATH
RUN pip install -r /mkdocs/requirements.txt

WORKDIR /k0s

# Expose MkDocs development server port
EXPOSE 8000

# Start development server by default
ENTRYPOINT ["mkdocs"]
CMD ["serve", "--dev-addr=0.0.0.0:8000"]
