# SPDX-FileCopyrightText: 2023 k0s authors
# SPDX-License-Identifier: Apache-2.0

name: "Build :: Image bundle"

on:
  workflow_call:
    inputs:
      image-bundle-name:
        type: string
        required: true
        description: The name of the image bundle to be built.
      image-bundle-platform:
        type: string
        required: true
        description: The platform suffix of the image bundle to be built.
      runs-on:
        type: string
        required: false
        description: The platform to build the image bundle on.
    outputs:
      cache-key:
        description: The image bundle's cache key.
        value: ${{ jobs.build.outputs.cache-key }}

env:
  MAKEFLAGS: -j

jobs:
  build:
    name: "${{ inputs.image-bundle-name }}-${{ inputs.image-bundle-platform }}"
    runs-on: ${{ inputs.runs-on || 'ubuntu-24.04' }}

    outputs:
      cache-key: ${{ steps.cache-image-bundle-calc-key.outputs.cache-key }}

    env:
      IMAGE_BUNDLE_NAME: ${{ inputs.image-bundle-name }}
      IMAGE_BUNDLE_PLATFORM: ${{ inputs.image-bundle-platform }}

    steps:
      - name: "Build :: Checkout"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: "Download :: k0s"
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ inputs.runs-on == 'ubuntu-24.04-riscv' && 'k0s-linux-riscv64' || 'k0s-linux-amd64' }}

      - name: "Download :: Image list"
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ inputs.image-bundle-name }}-images-${{ inputs.image-bundle-platform }}.txt

        # Capture the calculated image bundle source hash in a separate step, as
        # the hashFiles function is evaluated before the step execution. So all
        # the required files need to exist before that.
      - name: "Cache :: Image bundle :: Calculate cache key"
        id: cache-image-bundle-calc-key
        env:
          HASH_VALUE: ${{ hashFiles('Makefile', format('{0}-images-{1}.txt', inputs.image-bundle-name, inputs.image-bundle-platform), 'cmd/airgap/*', 'pkg/airgap/*') }}
        run: |
          printf 'cache-key=build-%s-image-bundle-%s-%s\n' "$IMAGE_BUNDLE_NAME" "$IMAGE_BUNDLE_PLATFORM" "$HASH_VALUE" >>"$GITHUB_OUTPUT"

      - name: "Cache :: Image bundle"
        id: cache-image-bundle
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: ${{ steps.cache-image-bundle-calc-key.outputs.cache-key }}
          path: ${{ inputs.image-bundle-name }}-image-bundle-${{ inputs.image-bundle-platform }}.tar

      - name: "Build :: Image bundle"
        if: steps.cache-image-bundle.outputs.cache-hit != 'true'
        env:
          DOCKER: ''
          EMBEDDED_BINS_BUILDMODE: none
        run: |
          chmod +x k0s
          make --touch k0s "$IMAGE_BUNDLE_NAME-images-$IMAGE_BUNDLE_PLATFORM.txt"
          make "$IMAGE_BUNDLE_NAME-image-bundle-$IMAGE_BUNDLE_PLATFORM.tar"

      - name: "Upload :: Image bundle"
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ inputs.image-bundle-name }}-image-bundle-${{ inputs.image-bundle-platform }}
          path: ${{ inputs.image-bundle-name }}-image-bundle-${{ inputs.image-bundle-platform }}.tar
          compression-level: 0
