name: Lint docs

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - '**.md'
      - .github/workflows/docs.yml
      - .markdownlint.jsonc
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - '**.md'
      - .github/workflows/docs.yml
      - .markdownlint.jsonc
jobs:
  lint:
    name: Lint markdown
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e # v20.0.0
        with:
          config: .markdownlint.jsonc
          globs: '**/*.md'
