name: Lint docs

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - '**.md'
      - .github/workflows/docs.yml
      - .markdownlint.jsonc
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - '**.md'
      - .github/workflows/docs.yml
      - .markdownlint.jsonc
jobs:
  lint:
    name: Lint markdown
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # for copyright linting
          persist-credentials: false

      - uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
        with:
          config: .markdownlint.jsonc
          globs: '**/*.md'

      - name: Check copyright headers
        run: WHAT=docs make lint-copyright
