name: Spellcheck
on:
  push:
    branches:
      - main
      - release-*
    paths:
      - '**.md'
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - '**.md'
jobs:
  spellcheck:
    name: Spellcheck markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Spellcheck Action
        uses: rojopolis/spellcheck-github-actions@0.41.0
            
